set(SIMULICORE_CMAKE_LINUX 0)
set(SIMULICORE_CMAKE_LINUX_X86_64 0)
set(SIMULICORE_CMAKE_LINUX_ARM64 0)

set(SIMULICORE_CMAKE_WIN32 0)
set(SIMULICORE_CMAKE_WIN32_X86_64 0)
set(SIMULICORE_CMAKE_WIN32_ARM64 0)

set(SIMULICORE_CMAKE_MACOS 0)
set(SIMULICORE_CMAKE_MACOS_X86_84 0)
set(SIMULICORE_CMAKE_MACOS_ARM64 0)

if((${CMAKE_SYSTEM_NAME} STREQUAL "Linux") AND (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "x86_64"))

	set(SIMULICORE_CMAKE_LINUX 1)
	set(SIMULICORE_CMAKE_LINUX_X86_64 1)
	add_compile_definitions(SIMULICORE_LINUX)
	add_compile_definitions(SIMULICORE_LINUX_X86_64)

elseif((${CMAKE_SYSTEM_NAME} STREQUAL "Windows") AND ((${CMAKE_SYSTEM_PROCESSOR} STREQUAL "AMD64") OR (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "x86_64")))

	set(SIMULICORE_CMAKE_WIN32 1)
	set(SIMULICORE_CMAKE_WIN32_X86_64 1)
	add_compile_definitions(SIMULICORE_WIN32)
	add_compile_definitions(SIMULICORE_WIN32_X86_64)

elseif((${CMAKE_SYSTEM_NAME} STREQUAL "Darwin") AND (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "arm64"))

	set(SIMULICORE_CMAKE_MACOS 1)
	set(SIMULICORE_CMAKE_MACOS_ARM64 1)
	add_compile_definitions(SIMULICORE_MACOS)
	add_compile_definitions(SIMULICORE_MACOS_ARM64)

else()

	message(FATAL_ERROR "Unsupported System: ${CMAKE_SYSTEM_NAME} (${CMAKE_SYSTEM_PROCESSOR})")

endif()
